[build-system]
requires = ["setuptools>=42", "wheel"]

[tool.black]
line-length = 79

[tool.ruff]
lint.select = [
    "E",
    "F",
    #"B",  # bugbear
]

[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = true
