#!/bin/bash
# Update the local robot_properties_fingers files

trifinger_simulation=$(dirname "$0")
robot_properties_fingers=$(ros2 pkg prefix robot_properties_fingers)/share/robot_properties_fingers
local_properties=${trifinger_simulation}/trifinger_simulation/robot_properties_fingers

rm -rf ${local_properties}/*
cp -r ${robot_properties_fingers}/meshes ${local_properties}
cp -r ${robot_properties_fingers}/urdf ${local_properties}

# The generated URDFs contain the absolute path to the original file.  Due to
# this, there will be a diff on all files if they are updated on a different
# machine, even if the actual content of the file did not change.  To avoid
# this, shorten the path, so that it is only relative to the
# robot_properties_fingers package (which should be the same on all
# machines/workspaces).

find ${local_properties} -name "*.urdf" -exec sed -i "s|\(This document was autogenerated by xacro from\) .*/\(robot_properties_fingers/.*\.xacro\)|\1 \2|" {} +
