# build docs using sphinx and deploy to branch gh-pages
name: Documentation (Test)
on:
  workflow_dispatch:

jobs:
  build_only:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy documentation
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: docs
          requirements_path: docs/requirements.txt
          publish: false
