# build docs using sphinx and deploy to branch gh-pages
name: Documentation
on:
  workflow_dispatch:

# NOTE: for some reason that is not clear to me, `pip install` of required
# packages (sphinx, etc.) was installing things to a weird location outside of
# PATH when the repo is checked out directly in the working dir.  The
# corresponding warning from pip:
#
#     WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and
#     sphinx-quickstart are installed in
#     '/home/runner/.local/lib/trifinger_simulation' which is not on PATH
#
# This resulted in the build to fail later one, as sphinx-build was not in the
# PATH.
#
# This is solved by checking out to a subdirectory "trifinger_simulation".

jobs:
  build_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v4
        with:
          path: trifinger_simulation
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build and deploy documentation
        uses: sphinx-notes/pages@v3
        with:
          checkout: false  # checkout is done manually above (see NOTE for reason)
          documentation_path: trifinger_simulation/docs
          requirements_path: trifinger_simulation/docs/requirements.txt
          publish: false
