# build docs using sphinx and deploy to branch gh-pages
name: Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to GitHub Pages (disable to only test the build)"
        type: boolean
        default: false

# NOTE: for some reason that is not clear to me, `pip install` of required
# packages (sphinx, etc.) was installing things to a weird location outside of
# PATH when the repo is checked out directly in the working dir.  The
# corresponding warning from pip:
#
#     WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and
#     sphinx-quickstart are installed in
#     '/home/runner/.local/lib/trifinger_simulation' which is not on PATH
#
# This resulted in the build to fail later one, as sphinx-build was not in the
# PATH.
#
# This is solved by checking out to a subdirectory "trifinger_simulation".

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v4
        with:
          path: trifinger_simulation
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build and deploy documentation
        uses: sphinx-notes/pages@v3
        with:
          checkout: false  # checkout is done manually above (see NOTE for reason)
          documentation_path: trifinger_simulation/docs
          requirements_path: trifinger_simulation/docs/requirements.txt
          publish: ${{ github.event_name == 'push' || github.event.inputs.publish == 'true' }}
