# build docs using sphinx and deploy to branch gh-pages
name: Pages
on:
  push:
    branches:
      - master

# NOTE: for some reason that is not clear to me, `pip install` of required
# packages (sphinx, etc.) was installing things to a weird location outside of
# PATH when the repo is checked out directly in the working dir.  The
# corresponding warning from pip:
#
#     WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and
#     sphinx-quickstart are installed in
#     '/home/runner/.local/lib/trifinger_simulation' which is not on PATH
#
# This resulted in the build to fail later one, as sphinx-build was not in the
# PATH.
#
# This is solved by checking out to a subdirectory "trifinger_simulation".

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/checkout@v2
      with:
        path: trifinger_simulation
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and commit documentation
      uses: sphinx-notes/pages@v2
      with:
        repository_path: trifinger_simulation
        requirements_path: docs/requirements.txt

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: trifinger_simulation

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
