name: PR TODO checks

on: pull_request

jobs:
  fixmes:
    name: New FIXMEs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for FIXMEs
      uses: luator/github_action_check_new_todos@v2
      with:
          label: FIXME
          base_ref: origin/${{ github.base_ref }}

  todos:
    name: New TODOs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for TODOs
      uses: luator/github_action_check_new_todos@v2
      with:
          label: TODO
          base_ref: origin/${{ github.base_ref }}
